spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/school_management
    driver-class-name: org.postgresql.Driver
    username: admin
    password: admin

  jpa:
    hibernate:
      ddl-auto: none
      dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    schemas: public
    clean-disabled: true  # Security: never clean database in production

  docker:
    compose:
      file: compose-dev.yml
