package com.xavier.smarteducationapi.tenant.application.command;

import lombok.Builder;
import lombok.Data;
import jakarta.validation.constraints.*;

/**
 * Command to update an existing tenant.
 *
 * @author Xavier Nhagumbe
 * @version 1.0
 * @since 2025-09-16
 */
@Data
@Builder
public class UpdateTenantCommand {

    @Email(message = "Invalid email format")
    private String primaryEmail;

    private String primaryPhone;

    private String street;

    private String neighborhood;

    private String city;

    private String province;

    private String postalCode;

    private String country;

    private String taxId;

    private String registrationNumber;

    // Getters are automatically generated by @Data annotation from Lombok
}